### ISSUE TITLE
No mention of `sulu:webspaces:init`

### ISSUE THREAD

**Issue by carltongibson** [sulu-io/sulu-docs#114]
I tried adding a new webspace. Didn't see any reference to `sulu:webspaces:init` in the docs. 

Fortunately it was mentioned on Slack before I ran to it but an **Adding a New Webspace** page would be a useful addition to the docs. 

1. Create file as per existing instructions. 
2. Clear cache
3. Run `sulu:webspaces:init`
4. ...

**Comment by wachterjohannes** [comment]
hmm you could also run `app/console sulu:build` because the init command is a part of it and is able to detect new webspaces (: but perhaps we could introduce a new build command `webspaces` or something!

**Comment by carltongibson** [comment]
Just one extra point here: my admin user didn't have permissions on the new webspace once I got it set up — so it didn't appear.

I probably did something wrong.

I resolved by manually adding the record in the DB, but that's not great.

**Comment by wachterjohannes** [comment]
you only have to add the permission to the role after creating the new webspace!

**Comment by carltongibson** [comment]
OK. Sure. But — my point here — none of this is documented. 

Most of it makes sense after a run through but there's still a barrier to entry. 

My thought here is that few (more) worked examples for key activities, such as adding a new/second webspace, would help new users (like myself) over that. 

 > ...perhaps we could introduce a new build command...

If you like... But the issue here is not the steps, but documenting the steps. (None of it is hard _per se_.) — If you add a new command, that would need documenting too. 

(Again, I'm mega-impressed with Sulu; here I'm just reporting the issues I've encountered; hopefully, that smooths the way for fellow-travellers.)

**Comment by wachterjohannes** [comment]
your right it should be documented (: i have only thought about how we could make it easier! this new build command could also clear the cache for webspaces and would help not to forget the necessary steps.

**Comment by berndhep** [comment]
@wachterjohannes @joemoe Please update the documentation with these infos.
