### ISSUE TITLE
Subdomains in Sulu 

### ISSUE THREAD

**Issue by Basti271** [sulu-io/sulu-docs#632]
Hi, I can't figure out how to add a sub-domain to achieve sth like you described here:
https://docs.sulu.io/en/2.2/book/introduction/components.html#webspaces

> Next, let’s assume that ACME Inc. wants to dedicate each language to its correspondent market by using top-level-domains. This would of course be more marketing oriented and search engine friendly. The English content would be published in www.acme.com, the German content in www.acme.de and the French content in www.acme.fr. Let’s go even further and say that each website’s design should be a little different, maybe with a different header color. The user and the search engine would now have 3 separate websites, each with 1 language and individual design but all with the same content-structure.
> 
> Any of these scenarios can be implemented with Sulu using one single webspace.

Is this missing in the docs?

Kind regards

**Comment by alexander-schranz** [comment]
@Basti271 you need to go through the getting start documentation there in the [example xml](https://docs.sulu.io/en/2.2/book/webspaces.html) you see how you can define the urls for a specific language.

So you can have then:

```xml
                        <url language="en">www.acme.com</url>
                        <url language="fr">www.acme.fr</url>
                        <url language="de">www.acme.de</url>
```

Let us know how we can improve this or create a pull request to make this easier for others to understand.

**Comment by Basti271** [comment]
Thanks for your answer! But how can I achieve the different colors that are
mentioned in the quote in have included  in my previous post?

Kind regards

Alexander Schranz <notifications@github.com> schrieb am Di., 2. März 2021,
21:06:

**Comment by alexander-schranz** [comment]
You have access to the requested locale under `app.request.locale` and can embed a different css based on that in twig or use a css selector like `html[lang=en]` to provide different colors for a specificblanguage.
If you create multiple webspaces you can also use different themes over the suluthemebunde which is build on top of the syliusthemebundle.

**Comment by Basti271** [comment]
Ah ye I was thinking about a key in the xml, should have figured that out
by myself 😁 guess my symfony knowledge ist a bit rusted. Thanks again!

Alexander Schranz <notifications@github.com> schrieb am Mi., 3. März 2021,
01:05:

**Comment by niklasnatter** [comment]
Closing this as solved - thanks for reaching out! 🙂
