### ISSUE TITLE
Discussion: Community Bundles in Doc

### ISSUE THREAD

**Issue by TheCadien** [sulu-io/sulu-docs#655]
I would like to start a small Discussion. What do you think about a Small area for List community bundles in the Doc ?
Like the Bundles Folder. 
https://github.com/sulu/sulu-docs/tree/2.x/bundles

Currently there are not so many, but I think that there are a few really helpful. I think especially of 
https://github.com/the-cocktail/SuluMegamenuBundle
https://github.com/the-cocktail/SuluSchemaOrgBundle

**Comment by niklasnatter** [comment]
Would be okay for me to add as section about non-core bundles 🙂 
We should also include the `SuluArticleBundle`, `SuluAutomationBundle`, ... there

**Comment by alexander-schranz** [comment]
I think there was some discussion here to add the bundles to our website and then output community bundles which are typed correctly with `"type": "sulu-bundle"` in there `composer.json`.

**Comment by TheCadien** [comment]
@alexander-schranz I really like the idea too, but do you have it planned for the near future ? I would otherwise as a transition times create a base doc and when the Ünbersicht on the side comes you could remove this again.

**Comment by alexander-schranz** [comment]
We need to discuss this first internal if how in which one we really can promote in the documentation. Could also be that we are only listing bundles of partners. And for all others just link to https://packagist.org/search/?query=&type=sulu-bundle. So at current state I would maybe just add a link to `packagist`.
