### ISSUE TITLE
Incorrect documentation on content type Location

### ISSUE THREAD

**Issue by domienjansen** [sulu-io/sulu-docs#763]
The documentation on content type Location (https://docs.sulu.io/en/2.5/reference/content-types/location.html) incorrectly states that the following attributes are available:

```
{{ content.location.latitude }}
{{ content.location.longitude }}
{{ content.location.street }}
{{ content.location.streetNumber }}
{{ content.location.zip }}
{{ content.location.city }}
{{ content.location.country }}
```

Yet in reality it should be:

```
{{ content.location.lat }}
{{ content.location.long }}
{{ content.location.street }}
{{ content.location.number }}
{{ content.location.code }}
{{ content.location.town }}
{{ content.location.country }}
{{ content.location.title }}
{{ content.location.zoom }}
```

**Comment by alexander-schranz** [comment]
@domienjansen thx for the issue. Do you want to provide a pull request to fix this. The target branch should be 2.4 here: https://github.com/sulu/sulu-docs/blob/2.4/reference/content-types/location.rst
